import org.jetbrains.changelog.Changelog

plugins {
    id 'java'
    id 'idea'
    id 'net.minecraftforge.gradle' version '7.+'
    id 'net.minecraftforge.renamer' version '1.+'
    id 'org.jetbrains.changelog' version '2.5.0'
    id 'com.gradleup.shadow' version '9.4.+'
}

apply from: 'gradle/scripts/helpers.gradle'

// Early Assertions
assertProperty 'mod_version'
assertProperty 'root_package'
assertProperty 'mod_id'
assertProperty 'mod_name'

assertSubProperties 'use_access_transformer', 'access_transformer_locations'
assertSubProperties 'use_mixins', 'mixin_booter_version', 'mixin_refmap'
assertSubProperties 'is_coremod', 'coremod_includes_mod', 'coremod_plugin_class_name'
assertSubProperties 'use_asset_mover', 'asset_mover_version'

setDefaultProperty 'use_jetbrains_annotations', false, false
setDefaultProperty 'generate_sources_jar', true, false
setDefaultProperty 'generate_javadocs_jar', true, false
setDefaultProperty 'extra_jvm_args', false, ''
setDefaultProperty 'extra_tweak_classes', false, ''

version = propertyString('mod_version')
group = propertyString('root_package')

base {
    archivesName.set(propertyString('mod_id'))
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
    if (propertyBool('generate_sources_jar')) {
        withSourcesJar()
    }
    if (propertyBool('generate_javadocs_jar')) {
        withJavadocJar()
    }
}

minecraft {
    mappings channel: 'stable', version: '39-1.12'
    runs {
        register('client') {
            workingDir = file('runs/client/')
        }
        register('server') {
            args '--nogui', '--port', 25565
            workingDir = file('runs/server/')
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    maven {
        name 'CleanroomMC Repository'
        url 'https://maven.cleanroommc.com'
    }
    exclusiveContent {
        forRepository {
            maven {
                name 'CleanroomMC CurseMaven'
                url 'https://curse.cleanroommc.com'
            }
        }
        filter {
            includeGroup 'curse.maven'
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name 'Modrinth'
                url 'https://api.modrinth.com/maven'
            }
        }
        filter {
            includeGroup 'maven.modrinth'
        }
    }
}

dependencies {
    implementation minecraft.dependency('net.minecraftforge:forge:1.12.2-14.23.5.2864')
    if (propertyBool('use_jetbrains_annotations')) {
        implementation 'org.jetbrains:annotations:26.1.0'
    }
    if (propertyBool('use_asset_mover')) {
        implementation "com.cleanroommc:assetmover:${propertyString('asset_mover_version')}"
    }
    if (propertyBool('use_mixins')) {
        def mixin = "zone.rong:mixinbooter:${propertyString('mixin_booter_version')}"

        implementation mixin
        annotationProcessor 'org.ow2.asm:asm-debug-all:5.2'
        annotationProcessor 'com.google.guava:guava:32.1.2-jre'
        annotationProcessor 'com.google.code.gson:gson:2.8.9'
        annotationProcessor (mixin) {
            transitive = false
        }
    }
    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

renamer.mappings.from minecraft.dependency.toSrgFile

apply from: 'gradle/scripts/dependencies.gradle'

processResources {

    inputs.property 'mod_id', propertyString('mod_id')
    inputs.property 'mod_name', propertyString('mod_name')
    inputs.property 'mod_version', propertyString('mod_version')
    inputs.property 'mod_description', propertyString('mod_description')
    inputs.property 'mod_authors', "${propertyStringList('mod_authors', ',').join(', ')}"
    inputs.property 'mod_credits', propertyString('mod_credits')
    inputs.property 'mod_url', propertyString('mod_url')
    inputs.property 'mod_update_json', propertyString('mod_update_json')
    inputs.property 'mod_logo_path', propertyString('mod_logo_path')
    inputs.property 'mixin_refmap', propertyString('mixin_refmap')
    inputs.property 'mixin_package', propertyString('mixin_package')
    inputs.property 'mixin_configs', propertyStringList('mixin_configs').join(' ')

    def filterList = ['mcmod.info', 'pack.mcmeta']
    filterList.addAll(propertyStringList('mixin_configs').collect(config -> "mixins.${config}.json" as String))

    filesMatching(filterList) { fcd ->
        fcd.expand(
                'mod_id': propertyString('mod_id'),
                'mod_name': propertyString('mod_name'),
                'mod_version': propertyString('mod_version'),
                'mod_description': propertyString('mod_description'),
                'mod_authors': "${propertyStringList('mod_authors', ',').join(', ')}",
                'mod_credits': propertyString('mod_credits'),
                'mod_url': propertyString('mod_url'),
                'mod_update_json': propertyString('mod_update_json'),
                'mod_logo_path': propertyString('mod_logo_path'),
                'mixin_refmap': propertyString('mixin_refmap'),
                'mixin_package': propertyString('mixin_package')
        )
    }
}

test {
    useJUnitPlatform()
    javaLauncher.set(javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(8)
    })
    testLogging {
        showStandardStreams = true
    }
}

compileTestJava {
    sourceCompatibility = targetCompatibility = 8
}

jar {
    manifest {
        def attribute_map = [:]
        if (propertyBool('is_coremod')) {
            attribute_map['FMLCorePlugin'] = propertyString('coremod_plugin_class_name')
            if (propertyBool('coremod_includes_mod')) {
                attribute_map['FMLCorePluginContainsFMLMod'] = true
                attribute_map['ForceLoadAsMod'] = true
            }
        }
        attributes(attribute_map)
    }
}

idea.module {
    inheritOutputDirs = true
    downloadJavadoc = downloadSources = true
}

String parserChangelog() {
    if (!file('CHANGELOG.md').exists()) {
        throw new GradleException('publish_with_changelog is true, but CHANGELOG.md does not exist in the workspace!')
    }
    String parsedChangelog = changelog.renderItem(
            changelog.get(propertyString('mod_version')).withHeader(false).withEmptySections(false),
            Changelog.OutputType.MARKDOWN)
    if (parsedChangelog.isEmpty()) {
        throw new GradleException('publish_with_changelog is true, but the changelog for the latest version is empty!')
    }
    return parsedChangelog
}

// apply from: 'gradle/scripts/publishing.gradle'
apply from: 'gradle/scripts/extra.gradle'

// Add various JVM arguments here for runtime
//    def args = ['-ea:' + group]
//    if (propertyBool('use_mixins')) {
//        args << '-Dmixin.hotSwap=true'
//        args << '-Dmixin.checks.interfaces=true'
//        args << '-Dmixin.debug.export=true'
//    }
//    extraRunJvmArguments.addAll(args)
//    extraRunJvmArguments.addAll(propertyStringList('extra_jvm_args'))
//
//    if (propertyBool('use_tags')) {
//        if (file('tags.properties').exists()) {
//            Properties props = new Properties().tap { it.load(file('tags.properties').newInputStream()); it }
//            if (!props.isEmpty()) {
//                injectedTags.set(props.collectEntries { k, v ->
//                        def interpolated = interpolate(v)
//                        if (interpolated == null || interpolated.isEmpty()) throw new GradleException("Empty tag value found for key: $k")
//                        [(k): interpolated]
//                    })
//            }
//        }
//    }
//}
